//
//  ViewController.m
//  playground
//
//  Created by Aslam Ansari on 01/12/15.
//  Copyright © 2015 Osmosys. All rights reserved.
//

#import "ViewController.h"
#import "gitDataAutoGenerated.h"


@interface ViewController ()

@property (strong, nonatomic) IBOutlet UILabel *BuildDate;
@property (strong, nonatomic) IBOutlet UILabel *CreatedDate;

@property (strong, nonatomic) IBOutlet UILabel *Version;
@property (strong, nonatomic) IBOutlet UILabel *Branch;
@property (strong, nonatomic) IBOutlet UILabel *Comments;
@property (strong, nonatomic) IBOutlet UILabel *URL;
@end

@implementation ViewController
@synthesize BuildDate,CreatedDate,Version,Branch,Comments,URL;

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    BuildDate.text = BUILD_DATE;
    CreatedDate.text = GIT_LAST_COMMIT_DATE;
    Version.text = [NSString stringWithFormat:@"%@%@%@", GIT_LAST_REPO_TAG,([GIT_LAST_REPO_TAG length]>0?@".":@"") , [GIT_LAST_COMMIT_HASH uppercaseString]];
    Branch.text = GIT_CURRENT_BRANCH;
    Comments.text = GIT_LAST_COMMIT_COMMENT;
    URL.Text=GIT_REPO_TAG;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
